config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    resources :meals
  end

  root "application#index"

  get "/auth/:provider/callback" => "sessions#create"
  get "/logout" => "sessions#destroy"

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  validates :name, :price, :order_id, :user_id, presence: true
  validates :price, numericality: true, allow_nil: true

  belongs_to :user
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  kinds = %w(Draft Finalized Ordered Delivered)
  validates :restaurant_name, presence: true
  validates :status, inclusion: { in: kinds }

  has_many :meals
  has_many :users, through: :meals

  scope :active, -> { where(status: 'Draft') }
  scope :history, -> { where.not(status: 'Draft') }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true

  has_many :meals
  has_many :orders

 def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :logged_in
 
  private
  def logged_in?
    !!current_user
  end
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in
    redirect_to root_path if session[:user_id].nil?
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :logged_in

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      flash[:notice] = "Meal added!"
      redirect_to @meal.order
    else
      flash[:error] = @meal.errors.full_messages.join(", ")
      redirect_to @meal.order
    end
  end

  def meal_params
    params.require(:meal).permit(:name, :price, :order_id, :user_id) 
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in
  # def index
  #   @orders = params[:type] == "history" ? Order.history : Order.active
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @meals = @order.meals
    @meal = Meal.new
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(restaurant_name: order_params[:restaurant_name], status: 'Draft')
 
    if @order.save
      redirect_to orders_path
    else
      render "new"
    end
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(status: order_params[:status])
      redirect_to orders_path
    else
      render "edit"
    end
  end

  def order_params
    params.require(:order).permit(:restaurant_name, :status) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def create     
    if auth = request.env["omniauth.auth"]     
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)     
      session[:user_id] = user.id     
      redirect_to root_url, :notice => "Signed in!"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

app/views/application/_header.html.haml
%nav.navbar.navbar-fixed-top.navbar-color
  .container
    .navbar-header
      = link_to "Happy Meal", root_path, id: "logo"
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
      #navbar-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right.desc
          - if logged_in?
            %li#account= current_user.name
            %li= link_to "Log out", logout_path
          - else
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = "Log in"
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  = link_to "with Facebook", "/auth/facebook/"
                %li
                  = link_to "with Github", "/auth/github/"

app/views/application/index.html.haml
- if current_user
  %h3= "Welcome to meal ordering coordination system Happy Meal"
  %br/
  %h3
    .btn.btn-default= link_to "Orders", orders_path
  %h3
    .btn.btn-default= link_to "New order", new_order_path
- else
  %h3= "To continue please log in via Facebook or Github account"

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-color">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Happy Meal", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Orders", orders_path %></li>
      </ul>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right desc">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path %></li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= "Log in" %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "with Facebook", root_path %>
              </li>
              <li>
                <%= link_to "with Github", "/auth/github/" %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HappyMeal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'application/header'
    .container
      = render 'application/flash'
      = yield

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      .alert.alert-danger
        The form contains #{pluralize(@order.errors.count, "error")}.
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :restaurant_name
    = f.text_field :restaurant_name, class: 'form-control'
  .form-group
    = f.label :status
    = f.select :status, ['Draft', 'Finalized', 'Ordered', 'Delivered']
  .form-group
    = f.submit class: 'form-control'

app/views/orders/_form2.html.haml
%h3 Add meal to order
= form_for [@order, @meal] do |f|
  - if @meal.errors.any?
    #error_explanation
      .alert.alert-danger
        The form contains #{pluralize(@meal.errors.count, "error")}.
      %ul
        - @meal.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :order_id, value: @order.id
  = f.hidden_field :user_id, value: current_user

  .container
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :price
      = f.text_field :price, class: 'form-control'
    .form-group
      = f.submit class: 'form-control'

app/views/orders/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1= "Edit"
    = render 'form'
    = link_to "Back", orders_path

app/views/orders/index.html.haml
%h1 Orders
%h3
  %div.btn-group
    .btn.btn-default= link_to "Active", '#', :id => 'active'
    .btn.btn-default= link_to "History", '#', :id => 'history'
%table.table.table-striped
  %tr
    %th Restaurant name
    %th Status
    %th{colspan: 2} Actions
  - for order in @orders
    %tr#mytable{:class => "#{if order.status == "Draft" then order.status else "Nondraft" end}", :style => "visibility: visible"}
      %td= order.restaurant_name
      %td= order.status
      %td= link_to "Edit", edit_order_path(order)
      %td= link_to "Show", order
  - end unless @orders.blank?
%h3
  .btn.btn-default= link_to "New order", new_order_path

app/views/orders/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 New order
    = render 'form'
    = link_to 'Back', orders_path

app/views/orders/show.html.haml
%h1
  Order from #{@order.restaurant_name}
%h2 Details
%p
  %strong Restaurant:
  = @order.restaurant_name
  %br/
  %strong Status:
  = @order.status
  %br/
%h2 Meals
%p
%table.table.table-striped
  %tr
    %th Name
    %th Price
  - for meal in @meals
    %tr
      %td= meal.name
      %td= meal.price
  - end unless @meals.blank?
= if @order.status == "Draft" and @meals.blank? then render 'form2' end
%p= link_to 'Back', orders_path